# Generated by Django 5.0.1 on 2024-08-21 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('type', models.CharField(choices=[('P', 'Practical'), ('T', 'Theoretical')], max_length=1)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('prn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('division', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('acad_year', models.IntegerField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcqs_marks', models.IntegerField()),
                ('short_answer_marks', models.IntegerField()),
                ('full_answer_marks', models.IntegerField()),
                ('partial_answer_marks', models.IntegerField()),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_marks', models.IntegerField()),
                ('organization_marks', models.IntegerField()),
                ('presentation_skills_marks', models.IntegerField()),
                ('visual_aids_marks', models.IntegerField()),
                ('response_to_questions_marks', models.IntegerField()),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'presentation',
            },
        ),
        migrations.CreateModel(
            name='Ppt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_marks', models.IntegerField()),
                ('organization_marks', models.IntegerField()),
                ('design_marks', models.IntegerField()),
                ('delivery_marks', models.IntegerField()),
                ('audience_engagement_marks', models.IntegerField()),
                ('qa_handling_marks', models.IntegerField()),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'ppt',
            },
        ),
        migrations.CreateModel(
            name='MarksTheory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mse_marks', models.IntegerField()),
                ('cce_marks', models.IntegerField()),
                ('ese_marks', models.IntegerField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.courses')),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'marks_theory',
            },
        ),
        migrations.CreateModel(
            name='MarksPrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciap_marks', models.IntegerField()),
                ('esep_marks', models.IntegerField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.courses')),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'marks_prac',
            },
        ),
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originality_marks', models.IntegerField()),
                ('relevance_impact_marks', models.IntegerField()),
                ('feasibility_marks', models.IntegerField()),
                ('implementation_strategy_marks', models.IntegerField()),
                ('creativity_problem_solving_marks', models.IntegerField()),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'innovation',
            },
        ),
        migrations.CreateModel(
            name='Gd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_knowledge_marks', models.IntegerField()),
                ('communication_skills_marks', models.IntegerField()),
                ('participation_contribution_marks', models.IntegerField()),
                ('collaboration_teamwork_marks', models.IntegerField()),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'gd',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empathy_problem_definition_marks', models.IntegerField()),
                ('ideation_marks', models.IntegerField()),
                ('prototyping_marks', models.IntegerField()),
                ('testing_feedback_marks', models.IntegerField()),
                ('reflection_iteration_marks', models.IntegerField()),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'design',
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('understanding_marks', models.IntegerField()),
                ('analysis_application_marks', models.IntegerField()),
                ('solution_recommendation_marks', models.IntegerField()),
                ('organization_structure_marks', models.IntegerField()),
                ('clarity_writing_quality_marks', models.IntegerField()),
                ('references_citation_marks', models.IntegerField()),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'case_study',
            },
        ),
    ]
